### ISSUE TITLE
obront - Interaction with OptimismPortal implementation will result in loss of funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#102]
obront

medium

# Interaction with OptimismPortal implementation will result in loss of funds

## Summary

OptimismPortal accepts user deposits and transfers them to L2. The precautions taken to avoid loss of funds using the implementation contract are completely ineffective.

## Vulnerability Detail

In `layer_one.go`, all the L2 predeploys are set up. OptimismPortal is constructed below:
```go
{
	// The implementation of the OptimismPortal is deployed
	// as being paused to prevent invalid usage of the network
	// as only the proxy should be used
	Name: "OptimismPortal",
	Args: []interface{}{
		predeploys.DevL2OutputOracleAddr,
		config.PortalGuardian,
		true, // _paused
		predeploys.DevSystemConfigAddr,
	},
},
```

Note that it is constructed as `paused`, and the documentation says this prevents invalid usage as interactions should be with the proxy.

However, the `paused` flag only affects these two functions:
1. `finalizeWithdrawalTransaction`
2. `proveWithdrawalTransaction`

While the following two functions ignore `paused`:
1. `depositTransaction`
2. `receive`

It actually doesn't prevent any loss of funds to pause the first two contracts, because there's nothing to prove or finalize. However as the latter two remain operational and can easily brick any funds sent to it.

Note that `OptimismPortal` will be a verified contract and is the cornerstone of the messaging architecture. It seems more than likely it shall be used directly and will cause loss of funds.

## Impact

Usage of the `OptimismPortal` implementation contract will result in loss of funds, contrary to safety precautions taken.

## Code Snippet

https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L426

## Tool used

Manual Review

## Recommendation

Consider checking that the two sensitive operations are only callable on the proxy contract.

**Comment by GalloDaSballo** [comment]
Technically correct

However pertains to the Logic and not the implementation so funds should not be at risk beside the ones sent incorrectly there

**Comment by hrishibhat** [comment]
Sponsor comment:
This is correct but is not an intended use of the system and is a user error. There are no instances where the user should directly call the implementation contract. This can be a low actionable to preventatively add an implmentation block.
