### ISSUE TITLE
prapandey031 - Address aliasing can result in L2 accounts already having ETH or address(0) while depositing L1 to L2

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#103]
prapandey031

high

# Address aliasing can result in L2 accounts already having ETH or address(0) while depositing L1 to L2

## Vulnerability Detail
In the depositTransaction() function in the OptimismPortal.sol the L1 contract addresses are aliased using AddressAliasHelper.sol ([in line 448 of OptimismPortal.sol](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L448)). The addresses are aliased in an unchecked solidity block ([in lines 29 to 31 of AddressAliasHelper.sol](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/vendor/AddressAliasHelper.sol#L29)). 

This could result in the resulting L2 aliased address as address(0) (due to overflow. Specifically, 0xEeeeffFfFffFFFfFFFFFFFffffffFffFFfFfEEeF address, if used as L1 contract address can generate address(0) after getting aliased with the given constant (0x1111000000000000000000000000000000001111)). Now, since the "from" account on L2 is address(0), it doesn't need to be minted with ETH for sending it to some other address on L2. This would allow an attacker to deposit a transaction on L1 through a contract at address 0xEeeeffFfFffFFFfFFFFFFFffffffFffFFfFfEEeF (this contract would call the depositTransaction() function in the OptimismPortal.sol) without sending ETH but setting the "_value" parameter to some high value (say 100 ETH). Now, the aliased address, and consequently, the "from" address on L2 would be address(0) (which has a lot of ETH). The transaction on L2 would get executed and the attacker's address on L2 would get 100 ETH without depositing any value on L1. Here, address(0) is taken for simplicity; in reality any address that has ETH on L2 would behave in the same way. The attacker just needs to reverse calculate the correct contract address on L1, that would call the depositTransaction() function in the OptimismPortal.sol.

## Impact
The attacker can drain ETH from accounts on L2 without depositing any value on L1.

## Code Snippet
The below contract generates a suitable contract address for getting address(0) on L2 as "from":

// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.6.0;

contract Test_1 {

    uint160 constant offset = uint160(0x1111000000000000000000000000000000001111);

    function check() external pure returns (address result) {

            result = address((2**160) - offset);
    }
}

The below code is a snippet from AddressAliasHelper.sol that checks for the validity of this issue:
// SPDX-License-Identifier: GPL-3.0

pragma solidity 0.8.15;

contract Test_2 {

    uint160 constant offset = uint160(0x1111000000000000000000000000000000001111);
    address l1address = 0xEeeeffFfFffFFFfFFFFFFFffffffFffFFfFfEEeF;

    /// @notice Utility function that converts the address in the L1 that submitted a tx to
    /// the inbox to the msg.sender viewed in the L2
    /// @param l1Address the address in the L1 that triggered the tx to L2
    /// @return l2Address L2 address as viewed in msg.sender
    function applyL1ToL2Alias(address l1Address) public pure returns (address l2Address) {
        unchecked {
            l2Address = address(uint160(l1Address) + offset);
        }
    }

    function check() external view {

        address from = applyL1ToL2Alias(l1address);
        assert(from == address(0));
    }
}

The screenshot attached clearly depicts that call to Test_2.check() function is successful. 

## Tool used
Remix IDE
Manual Review

## Recommendation
In the OptimismPortal.sol contract, there should be a check that _value == msg.value. This would force any depositor to pay on L1 to get equal value on L2.

![Result](https://user-images.githubusercontent.com/71516802/230629516-74f5e615-b379-4e8f-8352-f43378ee15c3.png)

**Comment by hrishibhat** [comment]
Sponsor comment:
This report is false. It is equally unlikely that an attacker will be able to mine the private key for the address `0xEeeeffFfFffFFFfFFFFFFFffffffFffFFfFfEEeF` as well as the address `0x0000000000000000000000000000000000000000` directly.
