### ISSUE TITLE
obront - Reduced performance when `l1Blocks` in BatchQueue is empty due to wrong CriticalError emission

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#109]
obront

medium

# Reduced performance when `l1Blocks` in BatchQueue is empty due to wrong CriticalError emission

## Summary

Critical error is emitted in the derivation pipeline instead of returning an EOF, which will degrade performance in an expected situation.

## Vulnerability Detail

In the L2 derivation pipeline, the BatchQueue is requested to produce a new batch with  `deriveNextBatch`. Note the code below:

```go
// deriveNextBatch derives the next batch to apply on top of the current L2 safe head,
// following the validity rules imposed on consecutive batches,
// based on currently available buffered batch and L1 origin information.
// If no batch can be derived yet, then (nil, io.EOF) is returned.
func (bq *BatchQueue) deriveNextBatch(ctx context.Context, outOfData bool, l2SafeHead eth.L2BlockRef) (*BatchData, error) {
	if len(bq.l1Blocks) == 0 {
		return nil, NewCriticalError(errors.New("cannot derive next batch, no origin was prepared"))
	}
	epoch := bq.l1Blocks[0]
	bq.log.Trace("Deriving the next batch", "epoch", epoch, "l2SafeHead", l2SafeHead, "outOfData", outOfData)
```

The code is supposed to return an EOF when a batch can't be derivated yet (as per docs), while it returns a `CriticalError` when something completely unexpected takes place (e.g. batch from the future).

The issue is that `len(bq.l1Blocks) == 0` is treated as a CriticalError, instead of returning an EOF. This situation is certainly not an unrecoverable error.

It will only be handled up the call stack in the Driver's eventLoop:
```go
} else if err != nil && errors.Is(err, derive.ErrCritical) {
	s.log.Error("Derivation process critical error", "err", err)
	return
```

## Impact

Reduced performance when `l1Blocks` in BatchQueue is empty.

## Code Snippet

https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/op-node/rollup/derive/batch_queue.go#L151

## Tool used

Manual Review

## Recommendation

Treat the situation similarly to `BatchUndecided`:
```go
if len(bq.l1Blocks) == 0 {
    return nil, io.EOF
}
```

**Comment by hrishibhat** [comment]
Sponsor comment:
The description is correct, but we enforce an invariant that L1Blocks is never empty
