### ISSUE TITLE
chaduke - bridgeERC20To() fails to check and make sure _to != msg.sender

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#11]
chaduke

medium

# bridgeERC20To() fails to check and make sure _to != msg.sender

## Summary
``bridgeERC20To()`` fails to check and make sure ``_to != msg.sender``. This check is important because if ``_to == msg.sender``, then ``bridgeERC20To()`` is reduced to ``bridgeERC20()`` but without the ``onlyEOA`` modifier protection.

## Vulnerability Detail

``bridgeERC20To()`` fails to check and make sure ``_to != msg.sender``. At the same time, there is no ``onlyEOA`` modifier protection.

[https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L264-L281](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L264-L281)

``bridgeERC20()`` has the ``onlyEOA`` protection. When ``_to == msg.sender``,  ``bridgeERC20To()`` is reduced to ``bridgeERC20()`` but without the ``onlyEOA`` modifier protection.

This error basically leads to a `bridgeERC20()`` but without ``onlyEOA`` protection version, which is not consistent with the design. 

## Impact

when ``_to == msg.sender``, it is important that only an EOA can initiate such transfer. However, such check is lacking. As a result, ``bridgeERC20To()``  might be initiated by a contract even when ``_to == msg.sender``. In the case that the other side does not have such a contract with the same address, the ERC20 tokens might get lost. 

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
Add the check ``_to != msg.sender`` to ``bridgeERC20To()`` :

```diff
 function bridgeERC20To(
        address _localToken,
        address _remoteToken,
        address _to,
        uint256 _amount,
        uint32 _minGasLimit,
        bytes calldata _extraData
    ) public virtual {

+     if(_to == msg.sender) revert CannotSendToYourself();  // @audit: EOA should use bridgeERC20() instead
        _initiateBridgeERC20(
            _localToken,
            _remoteToken,
            msg.sender,
            _to,
            _amount,
            _minGasLimit,
            _extraData
        );
    }
```

**Comment by GalloDaSballo** [comment]
QA because QA in previous contest

**Comment by hrishibhat** [comment]
Sponsor comment:
Bridging an ERC20 to a different address than the sender is the intention of this method. This is not a bug.
