### ISSUE TITLE
prapandey031 - Replay of L2ToL1 Messages due to absence of check for sent messages and overflow of msgNonce in the initiateWithdrawal() function of the L2ToL1MessagePasser.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#110]
prapandey031

high

# Replay of L2ToL1 Messages due to absence of check for sent messages and overflow of msgNonce in the initiateWithdrawal() function of the L2ToL1MessagePasser.sol

## Vulnerability Detail
The initiateWithdrawal() function of the L2ToL1MessagePasser.sol contract increments the msgNonce in an unchecked solidity block ([in lines 126 to 128](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol#L126)). This would result in the values of msgNonce to get repeated again after a certain number of withdrawals ((2**240) - 1) (due to overflow). Eventually, an attacker would replay the withdrawals with msgNonces as 0, 1, 2, ....... and so on, after the msgNonce gets overflowed. This could have been prevented if there was a check to revert the transaction if the sentMessages[withdrawalHash] would point to True.

## Impact
The withdrawals could get replayed 
## Tool used

Manual Review

## Recommendation
Revert the transaction if if the sentMessages[withdrawalHash] would point to True.

**Comment by GalloDaSballo** [comment]
INVALID because 2^240 prob costs more than all eth

You wouldn't be able to mine all of those nonces

**Comment by hrishibhat** [comment]
Sponsor comment:
This is correct, but it is a known outcome that this value will overflow. It is *incredibly* unlikely that the value ever reaches this point.
