### ISSUE TITLE
chaduke - _isUnsafeTarget() fails to exclude OTHER_MESSENGER

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#16]
chaduke

medium

# _isUnsafeTarget() fails to exclude OTHER_MESSENGER

## Summary
_isUnsafeTarget() fails to exclude OTHER_MESSENGER.

## Vulnerability Detail
The _isUnsafeTarget() exclude ``L1CrossDomainMessenger`` and ``PORTAL`` as unsafe address, but fails to exclude ``OTHER_MESSENGER``. 

[https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/L1CrossDomainMessenger.sol#L64-L66](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/L1CrossDomainMessenger.sol#L64-L66)

As a result, users might call function ``relayMessage()`` on target ``OTHER_MESSENGER`` directly.  This might not be desirable. 

## Impact
``_isUnsafeTarget()`` fails to exclude OTHER_MESSENGER, as a result, a user can still call  ``relayMessage()` using ``OTHER_MESSENGER``  as the target. 

## Tool used
VSCode

Manual Review

## Recommendation 
``OTHER_MESSENGER`` should be excluded as an unsafe target.

```diff
 function _isUnsafeTarget(address _target) internal view override returns (bool) {
-        return _target == address(this) || _target == address(PORTAL);
+        return _target == address(this) || _target == address(PORTAL) || OTHER_MESSENGER;
    }
```

**Comment by GalloDaSballo** [comment]
OTHER MESSENGER is in other chain, so it's not correct

Recommend closing

**Comment by hrishibhat** [comment]
Sponsor comment:
The other messenger address can be a different contract on the executed chain and shouldn't be considered unsafe.
