### ISSUE TITLE
chaduke - finalizeBridgeETH() falis to make sure _to != OTHER_BRIDGE

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#21]
chaduke

medium

# finalizeBridgeETH() falis to make sure _to != OTHER_BRIDGE

## Summary
``finalizeBridgeETH()`` falis to make sure ``_to != OTHER_BRIDGE``.

## Vulnerability Detail

Function ``finalizeBridgeETH()`` finalizes an ETH bridge on this chain. 

[https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L294-L310](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L294-L310)

However, it fails to check to make sure ``_to != OTHER_BRIDGE``. since we do not want to send ETH to 
``OTHER_BRIDGE``.

## Impact
Funds might get lost if send to ``OTHER_BRIDGE``.

## Code Snippet
See above

## Tool used
VScode

Manual Review

## Recommendation
Add the check that ``_to != OTHER_BRIDGE``.

```diff
 function finalizeBridgeETH(
        address _from,
        address _to,
        uint256 _amount,
        bytes calldata _extraData
    ) public payable onlyOtherBridge {
        require(msg.value == _amount, "StandardBridge: amount sent does not match amount required");
        require(_to != address(this), "StandardBridge: cannot send to self");
        require(_to != address(MESSENGER), "StandardBridge: cannot send to messenger");
+      require(_to != address(OTHER_BRIDGE), "StandardBridge: cannot send to OTHER_BRIDGE");

        // Emit the correct events. By default this will be _amount, but child
        // contracts may override this function in order to emit legacy events as well.
        _emitETHBridgeFinalized(_from, _to, _amount, _extraData);

        bool success = SafeCall.call(_to, gasleft(), _amount, hex"");
        require(success, "StandardBridge: ETH transfer failed");
    }
```

**Comment by GalloDaSballo** [comment]
Invalid because `OTHER_BRIDGE` will be on the other chain, so the transfer on finalize will send to a random / non-system contract

**Comment by hrishibhat** [comment]
Sponsor comment:
Finalizing bridged eth to other bridge is a user error, and is not a bug.
