### ISSUE TITLE
chaduke - proposalL2Outout() uses the wrong timestamp for the proposal

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#22]
chaduke

medium

# proposalL2Outout() uses the wrong timestamp for the proposal

## Summary
proposalL2Outout() uses the wrong timestamp for the proposal. It uses ``uint128(block.timestamp)``, the current time stamp, rather than ``computeL2Timestamp(_l2BlockNumber)``, which should be smaller than the current time stamp.

## Vulnerability Detail

proposeL2Output() accepts an outputRoot and the timestamp of the corresponding L2 block.

[https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol#L179-L229](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol#L179-L229)

However, we expect the proposal time stamp to be used should be the timestamp corresponding to ``_l2BlockNumber``, it uses the current time stamp instead:

```javascript
 l2Outputs.push(
            Types.OutputProposal({
                outputRoot: _outputRoot,
                timestamp: uint128(block.timestamp),
                l2BlockNumber: uint128(_l2BlockNumber)
            })
        );
```
As a result, the wrong timestamp is used. 

## Impact
The wrong time stamp is used for each proposal, which might lead to synchronization issues or unexpected system behavior.

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
use the timestamp for the block ``_l2BlockNumber`` instead. 

```diff
function proposeL2Output(
        bytes32 _outputRoot,
        uint256 _l2BlockNumber,
        bytes32 _l1BlockHash,
        uint256 _l1BlockNumber
    ) external payable {
        require(
            msg.sender == PROPOSER,
            "L2OutputOracle: only the proposer address can propose new outputs"
        );

        require(
            _l2BlockNumber == nextBlockNumber(),
            "L2OutputOracle: block number must be equal to next expected block number"
        );

        require(
            computeL2Timestamp(_l2BlockNumber) < block.timestamp,
            "L2OutputOracle: cannot propose L2 output in the future"
        );

        require(
            _outputRoot != bytes32(0),
            "L2OutputOracle: L2 output proposal cannot be the zero hash"
        );

        if (_l1BlockHash != bytes32(0)) {
            // This check allows the proposer to propose an output based on a given L1 block,
            // without fear that it will be reorged out.
            // It will also revert if the blockheight provided is more than 256 blocks behind the
            // chain tip (as the hash will return as zero). This does open the door to a griefing
            // attack in which the proposer's submission is censored until the block is no longer
            // retrievable, if the proposer is experiencing this attack it can simply leave out the
            // blockhash value, and delay submission until it is confident that the L1 block is
            // finalized.
            require(
                blockhash(_l1BlockNumber) == _l1BlockHash,
                "L2OutputOracle: block hash does not match the hash at the expected height"
            );
        }

        emit OutputProposed(_outputRoot, nextOutputIndex(), _l2BlockNumber, block.timestamp);

        l2Outputs.push(
            Types.OutputProposal({
                outputRoot: _outputRoot,
 -               timestamp: uint128(block.timestamp),
 +            timestamp: computeL2Timestamp(_l2BlockNumber),
                l2BlockNumber: uint128(_l2BlockNumber)
            })
        );
    }

```

**Comment by GalloDaSballo** [comment]
Invalid because:
- Timestamp is used to check if the output can be deleted / challenged, it should be the L1 ts

**Comment by hrishibhat** [comment]
Sponsor comment:
The timestamp associated with the output is intended to be the L1 timestamp rather than an L2 estimate in order to calculate the difference with the finalization interval.
