### ISSUE TITLE
rvierdiiev - L2OutputOracle constructor checks `_submissionInterval > _l2BlockTime` which is incorrect as one is block amount and another is time range

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#26]
rvierdiiev

medium

# L2OutputOracle constructor checks `_submissionInterval > _l2BlockTime` which is incorrect as one is block amount and another is time range

## Summary
L2OutputOracle constructor checks `_submissionInterval > _l2BlockTime` which is incorrect as one is block amount and another is time range. Because of that it will not be possible to construct L2OutputOracle with `SUBMISSION_INTERVAL <= L2_BLOCK_TIME`.
## Vulnerability Detail
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol#L90-L112
```solidity
    constructor(
        uint256 _submissionInterval,
        uint256 _l2BlockTime,
        uint256 _startingBlockNumber,
        uint256 _startingTimestamp,
        address _proposer,
        address _challenger,
        uint256 _finalizationPeriodSeconds
    ) Semver(1, 2, 0) {
        require(_l2BlockTime > 0, "L2OutputOracle: L2 block time must be greater than 0");
        require(
            _submissionInterval > _l2BlockTime,
            "L2OutputOracle: submission interval must be greater than L2 block time"
        );


        SUBMISSION_INTERVAL = _submissionInterval;
        L2_BLOCK_TIME = _l2BlockTime;
        PROPOSER = _proposer;
        CHALLENGER = _challenger;
        FINALIZATION_PERIOD_SECONDS = _finalizationPeriodSeconds;


        initialize(_startingBlockNumber, _startingTimestamp);
    }
```

`_submissionInterval` is amount of blocks that should be passed before new output can be provided.
`_l2BlockTime` is the time between 2 l2 blocks in seconds.

Because of that this comparison is incorrect.
```solidity
require(
            _submissionInterval > _l2BlockTime,
            "L2OutputOracle: submission interval must be greater than L2 block time"
        );
```

And it will not be possible to construct L2OutputOracle with `SUBMISSION_INTERVAL <= L2_BLOCK_TIME`. As [`SUBMISSION_INTERVAL `](https://github.com/ethereum-optimism/optimism/blob/f30376825c82f62b846590487fe46b7435213d37/specs/proposals.md#constants) value is not determined yet, it can be a problem if value should be less than `L2_BLOCK_TIME` or same.
## Impact
L2OutputOracle will not be constructed.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
You don't need that check.

**Comment by GalloDaSballo** [comment]
If block-time is 2s and you submit after more than 2 blocks then technically the check is fine as is

Check being superfluous is QA either way

**Comment by hrishibhat** [comment]
Sponsor comment:
The check should be removed but this is a low issue.
