### ISSUE TITLE
csanuragjain - Challenger role fails at `FINALIZATION_PERIOD_SECONDS`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#3]
csanuragjain

medium

# Challenger role fails at `FINALIZATION_PERIOD_SECONDS`

## Summary
Challenger must be allowed to delete the proposed output root till `FINALIZATION_PERIOD_SECONDS` as per codebase. But it seems `deleteL2Outputs` function disallows challenger to delete the output root at exactly `FINALIZATION_PERIOD_SECONDS` which is incorrect

## Vulnerability Detail
1. Let's see definition for `FINALIZATION_PERIOD_SECONDS` variable

```solidity
/**
     * @notice Minimum time (in seconds) that must elapse before a withdrawal can be finalized.
     */
    uint256 public immutable FINALIZATION_PERIOD_SECONDS;
```

2. This means `FINALIZATION_PERIOD_SECONDS` variable denotes the time after which challenge period is over
3. Let's confirm this with finalization check function

```solidity
function _isFinalizationPeriodElapsed(uint256 _timestamp) internal view returns (bool) {
        return block.timestamp > _timestamp + L2_ORACLE.FINALIZATION_PERIOD_SECONDS();
    }
```

4. As we can see User transaction is finalized after `_timestamp + L2_ORACLE.FINALIZATION_PERIOD_SECONDS()` interval has passed
5. Now lets see whether challenger can actually delete the l2 output at `FINALIZATION_PERIOD_SECONDS` using `deleteL2Outputs` function

```solidity
function deleteL2Outputs(uint256 _l2OutputIndex) external {
        require(
            msg.sender == CHALLENGER,
            "L2OutputOracle: only the challenger address can delete outputs"
        );

       ...
        // Do not allow deleting any outputs that have already been finalized.
        require(
            block.timestamp - l2Outputs[_l2OutputIndex].timestamp < FINALIZATION_PERIOD_SECONDS,
            "L2OutputOracle: cannot delete outputs that have already been finalized"
        );
```

6. As we can see here, if `FINALIZATION_PERIOD_SECONDS` has passed from `l2Outputs[_l2OutputIndex].timestamp` then the require condition will fail

```solidity

            block.timestamp - l2Outputs[_l2OutputIndex].timestamp < FINALIZATION_PERIOD_SECONDS,

// FINALIZATION_PERIOD_SECONDS< FINALIZATION_PERIOD_SECONDS = false
```

7. Hence Challenger will not be able to delete l2 output even when in finalization period

## Impact
Any discrepancy recognized at last moment `FINALIZATION_PERIOD_SECONDS` could not be challenged even though challenge period is not over. This can allow a malicious transaction to succeed.

## Code Snippet
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol#L154-L157

## Tool used
Manual Review

## Recommendation
Kindly revise the condition like below:

```solidity
require(
            block.timestamp - l2Outputs[_l2OutputIndex].timestamp <= FINALIZATION_PERIOD_SECONDS,
            "L2OutputOracle: cannot delete outputs that have already been finalized"
        );
```

**Comment by GalloDaSballo** [comment]
QA because it's 1 second
If you start with 0 index, then the check is correct with `<` because the 0th value should be included

QA either way imo

**Comment by hrishibhat** [comment]
Sponsor comment:
Since the output can be deleted at time T=0, the challenger role is able to delete for the full duration of the FINALIZATION_PERIOD_SECONDS.

**Comment by GalloDaSballo** [comment]
With the sponsor clarification, I agree that the interval is inclusive hence the check is correct
