### ISSUE TITLE
Bauer - User will lose funds if s/he sends ETH directly to the L2ToL1MessagePasser contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#34]
Bauer

high

# User will lose funds if s/he sends ETH directly to the L2ToL1MessagePasser contract

## Summary
The data forward to L1 target in the `L2ToL1MessagePasser.receive()` function  parameters is `bytes("")`, if user sends ETH directly to the `L2ToL1MessagePasser` contract, s/he will lose funds.

## Vulnerability Detail
The L2 protocol allows user to withdraw ETH by sending directly to this contract. Inside the `L2ToL1MessagePasser.receive()` function, the protocol calls the `initiateWithdrawal()` function to send message from L2 to L1. Howver ,the data forward to L1 target in the function parameters is `bytes("")`. And the msg.sender is not `L2CrossDomainMessenger` inside the `initiateWithdrawal()` function.  On the L1 side, the protocol will not be able to relay this message. Hence ,if user sends ETH directly to the `L2ToL1MessagePasser` contract, s/he will lose funds.
```solidity
  receive() external payable {
        initiateWithdrawal(msg.sender, RECEIVE_DEFAULT_GAS_LIMIT, bytes(""));
    }
function initiateWithdrawal(
        address _target,
        uint256 _gasLimit,
        bytes memory _data
    ) public payable {
        bytes32 withdrawalHash = Hashing.hashWithdrawal(
            Types.WithdrawalTransaction({
                nonce: messageNonce(),
                sender: msg.sender,
                target: _target,
                value: msg.value,
                gasLimit: _gasLimit,
                data: _data
            })
        );

        sentMessages[withdrawalHash] = true;

        emit MessagePassed(
            messageNonce(),
            msg.sender,
            _target,
            msg.value,
            _gasLimit,
            _data,
            withdrawalHash
        );

        unchecked {
            ++msgNonce;
        }
    }


```

## Impact
User may lose funds.
## Code Snippet
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol#L75-L77
## Tool used

Manual Review

**Comment by GalloDaSballo** [comment]
Looks invalid

Withdrawals do not require the CrossDomainMessenger

The default value ensures that the withdrawal will simply call to the target address

**Comment by hrishibhat** [comment]
Sponsor comment:
This report is false. Sending ETH to the `L2ToL1MessagePasser` contract sends a cross domain message with a target of `msg.sender`, which can be proven and finalized by the `OptimismPortal`, but not the `L1CrossDomainMessenger`, which I assume the reporter was referring to.
