### ISSUE TITLE
overflow427x - overflow427x – gasUsedDelta and baseFeeDelta can cause overflow/underflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#48]
overflow427x

medium

# overflow427x – gasUsedDelta and baseFeeDelta can cause overflow/underflow

overflow427x 

medium
## Summary
`gasUsedDelta` and `baseFeeDelta` in `_metered()` can cause overflow/underflow
## Vulnerability Detail
In `_metered()` the `gasUsedDelta` and `baseFeeDelta` are computed using integer arithmetic, there is no check to ensure that these values do not cause an overflow/underflow.
## Impact
Overflow and underflow of the values
## Code Snippet
https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/ResourceMetering.sol#L92-L114
## Tool used

Manual Review

## Recommendation
Add a check to ensure these values do not cause overflow and underflow

**Comment by GalloDaSballo** [comment]
GAS Math is capped at 2^32 so it's not realistic

**Comment by hrishibhat** [comment]
Sponsor comment:
The arithmetic is checked and cannot overflow bounds.
