### ISSUE TITLE
J4de - When L2 withdraws, if it is ERC20, it will return the ETH that the user may pay

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#53]
J4de

medium

# When L2 withdraws, if it is ERC20, it will return the ETH that the user may pay

## Summary

`L2StandardBridge.sol#withdraw` supports both ERC20 and ETH. If it is ERC20, it should return the ETH that the user may pay.

## Vulnerability Detail

```solidity
File: L2StandardBridge.sol
 96     function withdraw(
 97         address _l2Token,
 98         uint256 _amount,
 99         uint32 _minGasLimit,
100         bytes calldata _extraData
101     ) external payable virtual onlyEOA {
102         _initiateWithdrawal(_l2Token, msg.sender, msg.sender, _amount, _minGasLimit, _extraData);
103     }
```

`withdraw` is a `payable` function and further calls to `_initiateWithdrawal`.

```solidity
File: L2StandardBridge.sol
179     function _initiateWithdrawal(
180         address _l2Token,
181         address _from,
182         address _to,
183         uint256 _amount,
184         uint32 _minGasLimit,
185         bytes memory _extraData
186     ) internal {
187         if (_l2Token == Predeploys.LEGACY_ERC20_ETH) {
188             _initiateBridgeETH(_from, _to, _amount, _minGasLimit, _extraData);
189         } else {
190             address l1Token = OptimismMintableERC20(_l2Token).l1Token();
191             _initiateBridgeERC20(_l2Token, l1Token, _from, _to, _amount, _minGasLimit, _extraData);
192         }
193     }
```

`_initiateWithdrawal` supports both ETH and ERC20. Only in the case of withdraw ETH, the user needs to pay ETH. Therefore, if the user chooses ERC20, it is recommended to return the ETH that the user may pay.

## Impact

Users may lose ETH.

## Code Snippet

https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol#L179-L193

## Tool used

Manual Review

## Recommendation

It is recommended to return ETH or divide it into two interfaces, just like `L1StandardBridge.sol`.

**Comment by GalloDaSballo** [comment]
Recommended QA - Reliant on user mistake sending both value and token, arguably incorrect usage of code

**Comment by hrishibhat** [comment]
Sponsor comment:
False-but-actionable: Unintended withdrawal use.
