### ISSUE TITLE
HE1M - Messing up `from` or `sender` address on the receiver chain

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#65]
HE1M

medium

# Messing up `from` or `sender` address on the receiver chain

## Summary

It is possible to mess up the `from` or `sender` address on the receive chain if the contracts `OtimismPortal`, `L1StandardBridge`, `L1CrossDomainMessenger`, `L2ToL1MessagePasser`, `L2StandardBridge` and `L2CrossDomainMessenger` call each other.

## Vulnerability Detail

There are scenarios that mess up the `sender` or `from` parameters. Currently, the attack vector is not clear, but it provides attack surface:
 - **Scenario 1:** [During finalizing the ETH bridge on L1](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol#L216), if `_to` is equal to the address of `OtimismPortal`, the `L1StandardBridge` transfers ETH directly to `OptimismPortal`. In this case, the function [`receive()` ](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L197-L199) will be triggered, and the [`depositTransaction`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L464) will emit the relevant event, in which `from` is equal to alias of `L1StandardBridge` address. So, on L2 side, the initiator of the transaction will be the alias of `L1StandardBridge`.

 - **Scenario 2:** [During finalizing the withdrawal transaction on L1](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L397), if `_tx.target` is equal to `OptimismPortal` and `_tx.data` includes the data related to the function `depositTransaction` or an empty data, the `OtimismPortal` calls itself. Whether it calls `depositTransaction` or directly transfers ETH to itself. In both cases, the [`depositTransaction`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L464) will emit the relevant event, in which `from` is equal to the alias of `OptimismPortal` address. So, on L2 side, the initiator of the transaction will be the alias of `OptimismPortal`.

 - **Scenario 3:** [During finalizing the withdrawal transaction on L1](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L397), if `_tx.target` is equal to `L1CrossDomainMessenger` and `_tx.data` includes the data related to the function `sendMessage`, the `OtimismPortal` calls the function [`L1CrossDomainMessenger.sendMessage`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L247). In this case, on L2 side, the [`L2CrossDomainMessenger.relayMessage`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L291) will be triggered, while the [`_sender`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L360) is equal to the address of `OptimismPortal`.

 - **Scenario 4:** [During finalizing the withdrawal transaction on L1](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L397), if `_tx.target` is equal to `L1StandardBridge` and `_tx.data` includes the data related to the function `depositETHTo`, the `OptimismPortal` calls the function [`L1StandardBridge.depositETHTo`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol#L137). In this case, on L2 side, the [`L2StandardBridge.finalizeBridgeETH`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L294) will be triggered, while `_from` is equal to the address of `OptimismPortal`.

 - **Scenario 5:** [During relaying the message on L2](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L361), if `_target` is equal to `L2StandardBridge` and `_message` includes the data related to the function `L2StandardBridge.withdrawTo`, the `L2CrossDomainMessenger` calls the function [`L2StandardBridge.withdrawTo`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol#L121). In this case, on L1 side, the `L1StandardBridge.finalizeBridgeETH` will be triggered, while [`_from`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L295) is equal to the address of `L2CrossDomainMessenger`.

 - **Scenarion 6:** [During finalizing the ETH bridge on L2](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol#L143), if `_to` is equal to the address of `L2ToL1MessagePasser `, the `L2StandardBridge` transfers ETH directly to `L2ToL1MessagePasser `. In this case, the function [`receive()` ](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol#L75-L77) will be triggered, and the [`initiateWithdrawal`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol#L98) will emit the relevant event, in which `from` is equal to `L2StandardBridge` address. So, on L1 side, during finalizing the withdrawal transaction in `OptimismPortal`,  the [`_tx.sender`](https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L386) is equal to address of  `L2StandardBridge`.

Lets have an example of how to mess up the `from` or `sender` on the receiver chain. The following example is for the scenario 2:

Bob (a malicious user) calls `L2ToL1MessagePasser .initiateWithdrawal` on L2 with the following parameters:
 - `_target`: Address of `OptimismPortal` on L1
 - `_gasLimit`: large enough the execute the transaction on L1 succesfully
 - `_data`: `abi.encodeWithSignature("depositTransaction(address,uint256,uint64,bool,bytes)", address of the target on L2, the value needed to be transferred to the target, required gas to execute the transaction successfully on L2, whether or not to create contract, data needed to be transferred to the target on L2)`
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol#L98-L129

When this withdrawal transaction is going to be finalized on L1 in `OptimismPortal`, it triggers the call to itself and calls the function `OptimismPortal.depositTransaction`, because the parameter `_tx.target` is equal to address of `OptimismPortal`.
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L397

When the function `OptimismPortal.depositTransaction` is called, the `msg.sender` is equal to address of `OtimismPortal`, so the variable `from` will be set to alias of `OtimismPortal` address. 
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L426-L465

Finally, the `TransactionDeposited` event will be emitted so that the rollup node can derive a deposit. Please note that the parameter `from` is set to alias of `OtimismPortal` address.
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L95-L100

As a result, the receiver address on L2 will be called, or a contract will be created on L2 on behalf of `OptimismPortal` (in other words `from` will be equal to alias of `OtimismPortal` address).

## Impact
Currently, there is no clear risk. But if in the future some contracts are created on L2 relying on the sender of the other chain, there is attack surface to mess up these addresses.

## Tool used

Manual Review

## Recommendation
It is recommended to prevent calling unsafe targets or adding access control to critical function for all the scenarios explained above.

For example for scenario 2:

It is recommended to disallow calling unsafe targets in `OptimismPortal` to be on safe side:
```solidity
function finalizeWithdrawalTransaction(Types.WithdrawalTransaction memory _tx)
        external
        whenNotPaused
    {
        //...

        require(
            _isUnsafeTarget(_tx.target) == false,
            "OptimismPortal: cannot send message to blocked system address"
        );

        bool success = SafeCall.callWithMinGas(_tx.target, _tx.gasLimit, _tx.value, _tx.data);

        //...
    }

    function _isUnsafeTarget(address _target) internal view override returns (bool) {
        return _target == address(this);
    }
```

**Comment by GalloDaSballo** [comment]
QA because it requires using the portal in a way that is not intended, the user would be performing xChain calls back and forth without an intermediary contract, which is not intended and no loss was shown beside the message sent to the system contracts

**Comment by hrishibhat** [comment]
Sponsor comment:
Arbitrary calls is a design decision and the described issues are user errors.
