### ISSUE TITLE
Koolex - Deleting output proposals can not be paused by any role which could possibly lead to critical impact

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#68]
Koolex

medium

# Deleting output proposals can not be paused by any role which could possibly lead to critical impact

## Summary
The address of the challenger is immutable while deleting output proposals can not be paused by any role. This could lead to critical impact. Check below for details.

## Vulnerability Detail
The challenger can delete output proposals that are not finalized yet via `L2OutputOracle.deleteL2Outputs` method.
https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol#L141

The address of the challenger is immutable and set only once in the L2OutputOracle's `constructor`. Importantly, it can not be updated by any other roles in the system (e.g. Guardian, Sequencer ...etc).

```solidity
	SUBMISSION_INTERVAL = _submissionInterval;
	L2_BLOCK_TIME = _l2BlockTime;
	PROPOSER = _proposer;
	CHALLENGER = _challenger;
	FINALIZATION_PERIOD_SECONDS = _finalizationPeriodSeconds;

	initialize(_startingBlockNumber, _startingTimestamp);
```

The only way to update the address of the challenger is by upgrading the system. Check this note above the immutable `CHALLENGER`
```solidity
    /**
     * @notice The address of the challenger. Can be updated via upgrade.
     */
    address public immutable CHALLENGER;
```

In case of a leakage of challenger's private key, a malcious actor (who got the key) can mess up with the system by deleting all non-finalized output proposals. The actor can keep doing this till Optimism's team perform an upgrade process to update the challanger address which is not a prompt process as the upgrade needs to be done with care. Since no other roles (even the guardian) can stop the malcious actor, the system generally is broken till the upgrade is complete which is a big security impact and can be easily prevented (check the recommendation below).

It's worth mentioning that the guardian can pause proving and finalizing withdrawals in OptimismPortal. Thus, in case of an emerging issue, the gaurdian can pause withdrawals as a last resort. However, the guardian has no possibility to pause deleting L2OutputOracle's outputs in case of an emerging issue such as a key leakage.

## Impact
The system (especially the withdrawal) is broken till a new upgrade is done.

## Code Snippet

Check above

## Tool used

Manual Review

## Recommendation

Give the guardian (who is supposed to gaurd the system) the possibility to pause deleting output proposals. This way, deleting can be paused in case of emergency such as the situation described above. After the team finishes the upgrade, the guardian unpauses deleting. This prevent the system from getting broken in case the challenger's key is compromised.

Note: this is also applicable in case of proposer's key leakage. However, it has less critical impact since the proposals can always be challenged.

**Comment by GalloDaSballo** [comment]
Not convinced this falls within the rules of sherlock, you ultimately are assuming that CHALLENGER key can be leaked, the CHALLENGER may be a contract that allows multiple EOAs or Multisigs to perform the challenge

**Comment by hrishibhat** [comment]
Sponsor comment:
The challenger is an Optimism controlled actor and the contract can be upgraded as well.

**Comment by GalloDaSballo** [comment]
Closing per Sherlock rules around Governance being benign

**Comment by koolexcrypto** [comment]
Escalate for 10 USDC.

With all due respect, I think it should be considered as a valid medium because both [issue 75](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/75) and [issue 228](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/228) from previous contest have the challenger as Optimism controlled actor.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> With all due respect, I think it should be considered as a valid medium because both [issue 75](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/75) and [issue 228](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/228) from previous contest have the challenger as Optimism controlled actor.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
This issue is about a malicious challenger, while the above issues pointed out in the escalation clearly describe incorrect state changes that can be possible even under normal circumstances, which is not according to Optimism design. 
This issue is clearly different from those issues

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> This issue is about a malicious challenger, while the above issues pointed out in the escalation clearly describe incorrect state changes that can be possible even under normal circumstances, which is not according to Optimism design. 
> This issue is clearly different from those issues

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
