### ISSUE TITLE
Koolex - Estimating gas required to relay the message on both L1 and L2 is incorrect

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#77]
Koolex

medium

# Estimating gas required to relay the message on both L1 and L2 is incorrect

## Summary
Estimating gas required to relay the message on both L1 and L2 is incorrect

## Vulnerability Detail
The gas estimation for `L1CrossDomainMessenger.relayMessage` and `L2CrossDomainMessenger.relayMessage` doesn't take into account the line that clears the reentrancy lock for `versionedHash`
```solidity
 reentrancyLocks[versionedHash] = false;
```

This is the old code
```solidity
	if (success == true) {
		successfulMessages[versionedHash] = true;
		emit RelayedMessage(versionedHash);
	} else {
		failedMessages[versionedHash] = true;
		emit FailedRelayedMessage(versionedHash);

		// Revert in this case if the transaction was triggered by the estimation address. This
		// should only be possible during gas estimation or we have bigger problems. Reverting
		// here will make the behavior of gas estimation change such that the gas limit
		// computed will be the amount required to relay the message, even if that amount is
		// greater than the minimum gas limit specified by the user.
		if (tx.origin == Constants.ESTIMATION_ADDRESS) {
			revert("CrossDomainMessenger: failed to relay message");
		}
	}
```

And the new one is
```solidity
	if (success) {
		successfulMessages[versionedHash] = true;
		emit RelayedMessage(versionedHash);
	} else {
		failedMessages[versionedHash] = true;
		emit FailedRelayedMessage(versionedHash);

		// Revert in this case if the transaction was triggered by the estimation address. This
		// should only be possible during gas estimation or we have bigger problems. Reverting
		// here will make the behavior of gas estimation change such that the gas limit
		// computed will be the amount required to relay the message, even if that amount is
		// greater than the minimum gas limit specified by the user.
		if (tx.origin == Constants.ESTIMATION_ADDRESS) {
			revert("CrossDomainMessenger: failed to relay message");
		}
	}

	// Clear the reentrancy lock for `versionedHash`
	reentrancyLocks[versionedHash] = false;
```

As you can see in the old code, the revert is at the end to account for all Opcodes before. However, in the new code, it doesn't consider the last line `reentrancyLocks[versionedHash] = false` .

## Impact
Wrong estimation of the gas limit amount required to relay the message on both L1 and L2

## Code Snippet

https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L382

## Tool used

Manual Review

## Recommendation

 
Move the revert to the end, and add a check for the `success`. So it becomes as follows:

```solidity
		// Clear the reentrancy lock for `versionedHash`
		reentrancyLocks[versionedHash] = false;

		if (success == false && tx.origin == Constants.ESTIMATION_ADDRESS) {
			revert("CrossDomainMessenger: failed to relay message");
		}
```

**Comment by GalloDaSballo** [comment]
Valid, incorrect behaviour in estimating in my opinion

Due to discrepancy, I do recommend Medium Severity as the result of the estimate will most often result in Reverts when the output from the estimate is expected to be sufficient gas to prevent this scenario

**Comment by hrishibhat** [comment]
Sponsor comment:
Gas estimation is low actionable.

**Comment by zobront** [comment]
Escalate for 10 USDC

> As you can see in the old code, the revert is at the end to account for all Opcodes before. However, in the new code, it doesn't consider the last line reentrancyLocks[versionedHash] = false .

The premise here is incorrect. The previous implementation did not account for all opcodes, as a global reentrancy lock was set in the [modifier](https://github.com/sherlock-audit/2023-01-optimism/blob/568966b0a064d923ae723fb83ae2c45a3579c179/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L263). 

Even re-ordering won't cover all opcodes as there's always going to be some compiler-emitted opcodes for stack unwinding, etc before the function call returns. The point is, it is not feasible to completely count on the estimation, which is why a safety factor is added.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> > As you can see in the old code, the revert is at the end to account for all Opcodes before. However, in the new code, it doesn't consider the last line reentrancyLocks[versionedHash] = false .
> 
> The premise here is incorrect. The previous implementation did not account for all opcodes, as a global reentrancy lock was set in the [modifier](https://github.com/sherlock-audit/2023-01-optimism/blob/568966b0a064d923ae723fb83ae2c45a3579c179/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L263). 
> 
> Even re-ordering won't cover all opcodes as there's always going to be some compiler-emitted opcodes for stack unwinding, etc before the function call returns. The point is, it is not feasible to completely count on the estimation, which is why a safety factor is added.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by koolexcrypto** [comment]
Escalate for 10 USDC.

With all due respect to the contest competitors, I believe this is a valid medium due to the following reasons:
1. There is a practical call flow that results in OOG and as per [Sherlock's Criteria](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-considered-valid)
> Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or **there is a practical call flow that results in OOG can be considered a valid medium** or in cases of blocking all user funds forever maybe a valid high

2. There is a loss of funds and as per [to how to identify a medium issue on Sherlock](https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-medium-issue),
> Causes a loss of funds but requires certain external conditions or specific states

Please also note that it is not mentioned as a known issue or accepted risk anywhere in the [contest page](https://app.sherlock.xyz/audits/contests/63).

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> With all due respect to the contest competitors, I believe this is a valid medium due to the following reasons:
> 1. There is a practical call flow that results in OOG and as per [Sherlock's Criteria](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-considered-valid)
> > Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or **there is a practical call flow that results in OOG can be considered a valid medium** or in cases of blocking all user funds forever maybe a valid high
> 
> 2. There is a loss of funds and as per [to how to identify a medium issue on Sherlock](https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-medium-issue),
> > Causes a loss of funds but requires certain external conditions or specific states
> 
> Please also note that it is not mentioned as a known issue or accepted risk anywhere in the [contest page](https://app.sherlock.xyz/audits/contests/63). 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
Accepting the 1st escalation. As pointed out there is no change from the previous code wrt the reentrancy locks impacting the estimation. 
The estimation being incorrect in this case does not cause additional risk, The impact of this issue can be considered low.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid low
> Accepting the 1st escalation. As pointed out there is no change from the previous code wrt the reentrancy locks impacting the estimation. 
> The estimation being incorrect in this case does not cause additional risk, The impact of this issue can be considered low. 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
