### ISSUE TITLE
Koolex - LES Issue#175 from the previous contest isn't fixed.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#79]
Koolex

medium

# LES Issue#175 from the previous contest isn't fixed.

## Summary
LES Issue [175](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/175) from the previous contest isn't fixed. 

## Vulnerability Detail
The issue that was reported in the previous contest isn't fixed. The transaction is still not forwarded to the sequencer.

Here is the link of the issue:
https://github.com/sherlock-audit/2023-01-optimism-judging/issues/175

Please check https://github.com/ethereum-optimism/op-geth/blob/optimism/les/api_backend.go#L196-L198

## Impact
Check above

## Tool used

Manual Review

**Comment by koolexcrypto** [comment]
Escalate for 10 USDC.

I think it is as a valid medium as per [Judge's comment from previous contest judge](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/175#issuecomment-1452556147)
> This was an oversight on Optimism's part and there are markers that would suggest it should be in scope.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> I think it is as a valid medium as per [Judge's comment from previous contest judge](https://github.com/sherlock-audit/2023-01-optimism-judging/issues/175#issuecomment-1452556147)
> > This was an oversight on Optimism's part and there are markers that would suggest it should be in scope.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue
Although we understand the argument raised in the issue and its duplicates, given that this is an update contest, I think it is pretty clear from the comment in the previous contest that LES is out of scope, and is Sponsor disputed.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a valid issue
> Although we understand the argument raised in the issue and its duplicates, given that this is an update contest, I think it is pretty clear from the comment in the previous contest that LES is out of scope, and is Sponsor disputed.
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
