### ISSUE TITLE
rvierdiiev - Sequencer can censor l2 transactions starting from bedrock

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#8]
rvierdiiev

medium

# Sequencer can censor l2 transactions starting from bedrock

## Summary
Before bedrock update, user was able to push their transactions directly to `CanonicalTransactionChain` on L1 in order to avoid censorship by the sequencer. 
> Alternatively, users can skip the sequencer entirely and submit their transactions directly to the CanonicalTransactionChain via an Ethereum transaction. This is typically more expensive because the fixed cost of submitting this transaction is paid entirely by the user and is not amortized over many different transactions. However, this alternative submission method has the advantage of being resistant to censorship by the sequencer. Even if the sequencer is actively censoring a user, the user can always continue to use Optimism and recover any funds through this mechanism.

With bedrock update it's no longer possible, so sequencer can sensor transactions and users have no other option to include their transaction into the block in case if sequencer doesn't accept it.
> Transactions submitted directly to the sequnecer. These transactions are a lot cheaper to submit (because you do not need the expense of a separate L1 transaction), but of course they cannot be made censorship resistant, because the sequencer is the only entity that knows about them.
## Vulnerability Detail
See summary.
## Impact
Transaction censorship by the sequencer is allowed. User can bridge funds to L2 and then don't have ability to withdraw them to L1, as sequencer doesn't accept its transaction.
## Code Snippet
No code here.
## Tool used

Manual Review

## Recommendation
Think about ability for user to avoid censorship.

**Comment by GalloDaSballo** [comment]
Invalid per `Direct Protocol Owner/Admin rug pulls`

**Comment by hrishibhat** [comment]
Sponsor comment:
Deposit transactions replace the CTC, so the censorship vector does not exist.
