### ISSUE TITLE
Koolex - Legacy messages that are already relayed can still be finalized

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#81]
Koolex

medium

# Legacy messages that are already relayed can still be finalized

## Summary
Legacy messages that are already relayed can still be finalized.

## Vulnerability Detail
`L1CrossDomainMessenger.relayMessage` checks that the legacy version of the message has not already been relayed as follows:
```solidity
	// If the message is version 0, then it's a migrated legacy withdrawal. We therefore need
	// to check that the legacy version of the message has not already been relayed.
	if (version == 0) {
		bytes32 oldHash = Hashing.hashCrossDomainMessageV0(_target, _sender, _message, _nonce);
		require(
			successfulMessages[oldHash] == false,
			"CrossDomainMessenger: legacy withdrawal already relayed"
		);
	}
```

Therefore, if you try to relay a message that's already been relayed, it will revert. However, `L1CrossDomainMessenger.relayMessage` has to be called for the first time by `OptimismPortal.finalizeWithdrawalTransaction`. 
This means `finalizeWithdrawalTransaction` can still succeed for already relayed legacy messages. That's because `finalizeWithdrawalTransaction` doesn't care if the call succeeds or not. And for legacy already relayed messages, `relayMessage` will always revert. This causes unnecessary loss of gas and also amplifies the volume of withdrawals finalizations. 

## Impact
Relayers will lose unnecessary amount of gas caused by successfully finalizing already relayed legacy messages. If a relayer is relaying bulk of legacy messages, then the loss is non-trivial.

## Code Snippet

https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L307-L313

## Tool used

Manual Review

## Recommendation

On migration, hash legacy messages (that are already relayed) and mark them as finalized. This way, `OptimismPortal.finalizeWithdrawalTransaction` will revert for those messages.

**Comment by koolexcrypto** [comment]
Escalate for 10 USDC.

With respect to GalloDaSballo's comment, it is unreasonable to be low because relayed legacy messages shouldn't be finlaized twice. It is incorrect and not an intended behaviour by design as it is a key property according to the [Security Considerations of withdrawal verification](https://github.com/ethereum-optimism/optimism/blob/develop/specs/withdrawals.md#security-considerations)
> It should only be possible to finalize the withdrawal once.


Morever, relaying bulk of legacy messages once again (for no reason) causes unnecessary loss of funds dedicated for the gas. And since this is on L1, it has non-negligible and uncheap cost.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> With respect to GalloDaSballo's comment, it is unreasonable to be low because relayed legacy messages shouldn't be finlaized twice. It is incorrect and not an intended behaviour by design as it is a key property according to the [Security Considerations of withdrawal verification](https://github.com/ethereum-optimism/optimism/blob/develop/specs/withdrawals.md#security-considerations)
> > It should only be possible to finalize the withdrawal once.
> 
> 
> Morever, relaying bulk of legacy messages once again (for no reason) causes unnecessary loss of funds dedicated for the gas. And since this is on L1, it has non-negligible and uncheap cost.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
The impact of the issue is low as the call reverts and there are no other implications of this. 
Additionally, Sponsor's comment points out the Lead judge's view:
>This is a low issue and doesn't impact the system.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> The impact of the issue is low as the call reverts and there are no other implications of this. 
> Additionally, Sponsor's comment points out the Lead judge's view:
> >This is a low issue and doesn't impact the system.
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
